/* eslint-disable @typescript-eslint/no-explicit-any */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Types (mirrored from page.tsx) ─────────────────────────────────
interface DimensionItem { id: string; name: string; score: number; maxScore: number; status: string; detail: string; }
interface Dimension { score: number; maxScore: number; pct: number; items: DimensionItem[]; }
interface FrameworkScore { score: number; grade: string; dimensions: Record<string, Dimension>; vetosTriggered: string[]; }
interface Opportunity { priority: string; title: string; category: string; currentState: string; targetState: string; impact: string; effort: string; steps: string[]; }
interface CompetitorInfo { name: string; rating: number; reviews: number; photos: number; strengths: string[]; yourAdvantage: string[]; }

interface AuditReport {
  localImpact: FrameworkScore;
  serpTrust: FrameworkScore;
  seoHealthIndex: { score: number; grade: string; formula: string };
  geoGrid: { solv: number; avgRank: number; summary: string; topCompetitors: Array<{ name: string; appearances: number }> };
  opportunities: Opportunity[];
  competitorAnalysis: { summary: string; competitors: CompetitorInfo[] };
  keywordInsights: {
    summary: string;
    rankingKeywords: Array<{ keyword: string; position: number; volume: number }>;
    suggestedKeywords: Array<{ keyword: string; rationale: string; competition: string }>;
  };
  executiveSummary: string;
  rawGeoGrid: any;
  rawDirectories: Array<{ name: string; url: string; found: boolean | null; napCorrect: boolean | null; claimed: boolean | null }>;
  rawTechnical: any;
  rawKeywords: Array<{ keyword: string; position: number; searchVolume: number; url: string }>;
  rawKeywordsTotal: number;
  rawETV: number;
  meta: { businessName: string; location: string; keyword: string; websiteUrl: string | null; auditDate: string };
}

// ─── Color helpers ──────────────────────────────────────────────────
const BRAND = {
  navy: [15, 23, 42] as [number, number, number],
  accent: [56, 189, 248] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  gray: [148, 163, 184] as [number, number, number],
  darkBg: [30, 41, 59] as [number, number, number],
};

function statusColor(status: string): [number, number, number] {
  switch (status) {
    case "excellent": return [16, 185, 129];
    case "good": return [59, 130, 246];
    case "fair": return [245, 158, 11];
    case "weak": return [249, 115, 22];
    case "absent": return [239, 68, 68];
    case "critical": return [220, 38, 38];
    default: return [148, 163, 184];
  }
}

function priorityColorRgb(p: string): [number, number, number] {
  switch (p) {
    case "critical": return [239, 68, 68];
    case "high": return [249, 115, 22];
    case "medium": return [245, 158, 11];
    default: return [59, 130, 246];
  }
}

function scoreColorRgb(score: number): [number, number, number] {
  if (score >= 70) return [16, 185, 129];
  if (score >= 40) return [245, 158, 11];
  return [239, 68, 68];
}

// ─── Dimension label maps ───────────────────────────────────────────
const LOCAL_IMPACT_LABELS: Record<string, string> = {
  listingQuality: "Listing Quality", onlineReviews: "Online Reviews",
  citationConsistency: "Citation Consistency", authoritySignals: "Authority Signals",
  localContent: "Local Content", integratedVisibility: "Integrated Visibility",
  performance: "Performance", tracking: "Tracking",
};
const SERP_TRUST_LABELS: Record<string, string> = {
  technicalFoundation: "Technical Foundation", rankingSignals: "Ranking Signals",
  userExperience: "User Experience", searchAuthority: "Search Authority",
  trustAiReadiness: "Trust & AI Readiness",
};

// ─── Main export ────────────────────────────────────────────────────
export function generateAuditPdf(report: AuditReport) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = 0;

  function addFooter() {
    const pages = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.gray);
      doc.text(`Generated by RankedFirst.ai`, margin, pageH - 8);
      doc.text(`Page ${i} of ${pages}`, pageW - margin, pageH - 8, { align: "right" });
    }
  }

  function checkPage(needed: number) {
    if (y + needed > pageH - 20) { doc.addPage(); y = 20; }
  }

  function sectionHeader(title: string) {
    checkPage(20);
    y += 8;
    doc.setFontSize(14);
    doc.setTextColor(...BRAND.accent);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(...BRAND.accent);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentW, y);
    y += 6;
  }

  function label(text: string, x: number, yPos: number) {
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.gray);
    doc.setFont("helvetica", "normal");
    doc.text(text, x, yPos);
  }

  function value(text: string, x: number, yPos: number, color?: [number, number, number]) {
    doc.setFontSize(11);
    doc.setTextColor(...(color ?? BRAND.navy));
    doc.setFont("helvetica", "bold");
    doc.text(text, x, yPos);
  }

  // ═══════════════════════════════════════════════════════════════════
  // PAGE 1: HEADER + OVERVIEW
  // ═══════════════════════════════════════════════════════════════════

  // Dark header band
  doc.setFillColor(...BRAND.navy);
  doc.rect(0, 0, pageW, 50, "F");

  // Brand name
  doc.setFontSize(22);
  doc.setTextColor(...BRAND.white);
  doc.setFont("helvetica", "bold");
  doc.text("RankedFirst.ai", margin, 18);
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.gray);
  doc.setFont("helvetica", "normal");
  doc.text("Local SEO Audit Report", margin, 26);

  // Score circle (right side)
  const score = report.seoHealthIndex?.score ?? 0;
  const scoreCol = scoreColorRgb(score);
  doc.setFontSize(32);
  doc.setTextColor(...scoreCol);
  doc.setFont("helvetica", "bold");
  doc.text(String(score), pageW - margin - 25, 22, { align: "center" });
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.gray);
  doc.text(`Grade: ${report.seoHealthIndex?.grade ?? "N/A"}`, pageW - margin - 25, 30, { align: "center" });

  // Business info bar
  doc.setFillColor(...BRAND.darkBg);
  doc.rect(0, 50, pageW, 14, "F");
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.white);
  doc.setFont("helvetica", "bold");
  doc.text(report.meta.businessName, margin, 59);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.gray);
  const metaLine = `${report.meta.location}  ·  "${report.meta.keyword}"  ·  Audited ${new Date(report.meta.auditDate).toLocaleDateString()}`;
  doc.text(metaLine, margin, 59 + 5);

  y = 72;

  // Vetos
  const vetos = [...(report.localImpact?.vetosTriggered ?? []), ...(report.serpTrust?.vetosTriggered ?? [])];
  if (vetos.length > 0) {
    for (const v of vetos) {
      doc.setFillColor(239, 68, 68);
      doc.roundedRect(margin, y, contentW, 7, 1, 1, "F");
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.white);
      doc.setFont("helvetica", "bold");
      doc.text(`⚠ CRITICAL: ${v}`, margin + 3, y + 5);
      y += 9;
    }
    y += 2;
  }

  // Two sub-scores
  const halfW = (contentW - 4) / 2;
  // LOCAL-IMPACT box
  doc.setFillColor(245, 245, 250);
  doc.roundedRect(margin, y, halfW, 22, 2, 2, "F");
  label("LOCAL-IMPACT", margin + 4, y + 6);
  const liScore = report.localImpact?.score ?? 0;
  value(`${liScore} / 100`, margin + 4, y + 15, scoreColorRgb(liScore));
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.gray);
  doc.text(`Grade: ${report.localImpact?.grade ?? "N/A"}`, margin + halfW - 4, y + 15, { align: "right" });

  // SERP-TRUST box
  const stX = margin + halfW + 4;
  doc.setFillColor(245, 245, 250);
  doc.roundedRect(stX, y, halfW, 22, 2, 2, "F");
  label("SERP-TRUST", stX + 4, y + 6);
  const stScore = report.serpTrust?.score ?? 0;
  value(`${stScore} / 100`, stX + 4, y + 15, scoreColorRgb(stScore));
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.gray);
  doc.text(`Grade: ${report.serpTrust?.grade ?? "N/A"}`, stX + halfW - 4, y + 15, { align: "right" });

  y += 28;

  // Executive Summary
  sectionHeader("Executive Summary");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(report.executiveSummary ?? "", contentW);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 4.5 + 4;

  if (report.seoHealthIndex?.formula) {
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.gray);
    doc.text(`Formula: ${report.seoHealthIndex.formula}`, margin, y);
    y += 6;
  }

  // ═══════════════════════════════════════════════════════════════════
  // LOCAL-IMPACT DIMENSIONS
  // ═══════════════════════════════════════════════════════════════════
  sectionHeader("LOCAL-IMPACT Framework");

  function renderDimension(dimKey: string, dim: Dimension, labels: Record<string, string>) {
    checkPage(20);
    const dimLabel = labels[dimKey] ?? dimKey;
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.navy);
    doc.setFont("helvetica", "bold");
    doc.text(`${dimLabel}  —  ${dim.score}/${dim.maxScore} (${dim.pct}%)`, margin, y);
    y += 5;

    // Filter out unknown/absent items for cleaner output? No — show them all.
    const visibleItems = (dim.items ?? []).filter(it => it.status !== "unknown");
    if (visibleItems.length > 0) {
      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["ID", "Item", "Score", "Status", "Detail"]],
        body: visibleItems.map(it => [
          it.id, it.name, `${it.score}/${it.maxScore}`, it.status,
          it.detail?.length > 80 ? it.detail.slice(0, 80) + "..." : (it.detail || "—"),
        ]),
        styles: { fontSize: 7, cellPadding: 1.5, overflow: "linebreak" },
        headStyles: { fillColor: BRAND.navy, textColor: BRAND.white, fontStyle: "bold" },
        columnStyles: {
          0: { cellWidth: 12 },
          1: { cellWidth: 28 },
          2: { cellWidth: 14, halign: "center" },
          3: { cellWidth: 16, halign: "center" },
          4: { cellWidth: "auto" },
        },
        didParseCell: (data: any) => {
          if (data.section === "body" && data.column.index === 3) {
            const status = data.cell.raw as string;
            data.cell.styles.textColor = statusColor(status);
            data.cell.styles.fontStyle = "bold";
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    } else {
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.gray);
      doc.text("No scored items in this dimension.", margin + 4, y);
      y += 6;
    }
  }

  if (report.localImpact?.dimensions) {
    for (const [key, dim] of Object.entries(report.localImpact.dimensions)) {
      renderDimension(key, dim, LOCAL_IMPACT_LABELS);
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // SERP-TRUST DIMENSIONS
  // ═══════════════════════════════════════════════════════════════════
  sectionHeader("SERP-TRUST Framework");

  if (report.serpTrust?.dimensions) {
    for (const [key, dim] of Object.entries(report.serpTrust.dimensions)) {
      renderDimension(key, dim, SERP_TRUST_LABELS);
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // OPPORTUNITIES
  // ═══════════════════════════════════════════════════════════════════
  if (report.opportunities?.length > 0) {
    sectionHeader("Opportunities");

    for (const opp of report.opportunities) {
      checkPage(35);
      // Priority badge
      const pc = priorityColorRgb(opp.priority);
      doc.setFillColor(...pc);
      doc.roundedRect(margin, y - 3, 22, 5, 1, 1, "F");
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.white);
      doc.setFont("helvetica", "bold");
      doc.text(opp.priority.toUpperCase(), margin + 11, y, { align: "center" });

      doc.setFontSize(10);
      doc.setTextColor(...BRAND.navy);
      doc.text(opp.title, margin + 26, y);
      y += 5;

      doc.setFontSize(7);
      doc.setTextColor(...BRAND.gray);
      doc.text(`Impact: ${opp.impact}  ·  Effort: ${opp.effort}  ·  Category: ${opp.category}`, margin + 4, y);
      y += 4;

      if (opp.currentState) {
        doc.setFontSize(7);
        doc.setTextColor(100, 100, 100);
        doc.text(`Current: ${opp.currentState}`, margin + 4, y);
        y += 3.5;
      }
      if (opp.targetState) {
        doc.text(`Target: ${opp.targetState}`, margin + 4, y);
        y += 3.5;
      }

      if (opp.steps?.length > 0) {
        for (const step of opp.steps) {
          checkPage(5);
          const stepLines = doc.splitTextToSize(`• ${step}`, contentW - 8);
          doc.setFontSize(7);
          doc.setTextColor(60, 60, 60);
          doc.setFont("helvetica", "normal");
          doc.text(stepLines, margin + 6, y);
          y += stepLines.length * 3.2;
        }
      }
      y += 4;
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // COMPETITORS
  // ═══════════════════════════════════════════════════════════════════
  if (report.competitorAnalysis?.competitors?.length > 0) {
    sectionHeader("Competitor Analysis");

    doc.setFontSize(8);
    doc.setTextColor(60, 60, 60);
    doc.setFont("helvetica", "normal");
    if (report.competitorAnalysis.summary) {
      const sumLines = doc.splitTextToSize(report.competitorAnalysis.summary, contentW);
      doc.text(sumLines, margin, y);
      y += sumLines.length * 3.5 + 4;
    }

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Competitor", "Rating", "Reviews", "Photos", "Strengths"]],
      body: report.competitorAnalysis.competitors.map(c => [
        c.name, String(c.rating), String(c.reviews), String(c.photos),
        (c.strengths ?? []).join(", ").slice(0, 100),
      ]),
      styles: { fontSize: 7, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: BRAND.navy, textColor: BRAND.white, fontStyle: "bold" },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // ═══════════════════════════════════════════════════════════════════
  // KEYWORDS
  // ═══════════════════════════════════════════════════════════════════
  if (report.keywordInsights) {
    sectionHeader("Keyword Insights");

    if (report.keywordInsights.summary) {
      doc.setFontSize(8);
      doc.setTextColor(60, 60, 60);
      doc.setFont("helvetica", "normal");
      const kwSumLines = doc.splitTextToSize(report.keywordInsights.summary, contentW);
      doc.text(kwSumLines, margin, y);
      y += kwSumLines.length * 3.5 + 4;
    }

    if (report.keywordInsights.rankingKeywords?.length > 0) {
      checkPage(15);
      doc.setFontSize(9);
      doc.setTextColor(...BRAND.navy);
      doc.setFont("helvetica", "bold");
      doc.text("Ranking Keywords", margin, y);
      y += 4;

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["Keyword", "Position", "Search Volume"]],
        body: report.keywordInsights.rankingKeywords.slice(0, 20).map(kw => [
          kw.keyword, String(kw.position), String(kw.volume),
        ]),
        styles: { fontSize: 7, cellPadding: 1.5 },
        headStyles: { fillColor: BRAND.navy, textColor: BRAND.white, fontStyle: "bold" },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }

    if (report.keywordInsights.suggestedKeywords?.length > 0) {
      checkPage(15);
      doc.setFontSize(9);
      doc.setTextColor(...BRAND.navy);
      doc.setFont("helvetica", "bold");
      doc.text("Suggested Keywords", margin, y);
      y += 4;

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["Keyword", "Rationale", "Competition"]],
        body: report.keywordInsights.suggestedKeywords.map(kw => [
          kw.keyword, kw.rationale?.slice(0, 80) || "—", kw.competition || "—",
        ]),
        styles: { fontSize: 7, cellPadding: 1.5, overflow: "linebreak" },
        headStyles: { fillColor: BRAND.navy, textColor: BRAND.white, fontStyle: "bold" },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // GEO-GRID SUMMARY
  // ═══════════════════════════════════════════════════════════════════
  if (report.geoGrid) {
    sectionHeader("Geo-Grid Analysis");
    doc.setFontSize(8);
    doc.setTextColor(60, 60, 60);
    doc.setFont("helvetica", "normal");

    doc.text(`Share of Local Voice (SoLV): ${report.geoGrid.solv}%`, margin, y); y += 4;
    doc.text(`Average Rank: ${report.geoGrid.avgRank > 0 ? `#${report.geoGrid.avgRank}` : "Not found"}`, margin, y); y += 4;

    if (report.geoGrid.summary) {
      const gLines = doc.splitTextToSize(report.geoGrid.summary, contentW);
      doc.text(gLines, margin, y);
      y += gLines.length * 3.5 + 2;
    }

    if (report.geoGrid.topCompetitors?.length > 0) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.text("Top Competitors at Grid Points:", margin, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      for (const tc of report.geoGrid.topCompetitors.slice(0, 5)) {
        doc.text(`• ${tc.name} — ${tc.appearances}/9 appearances`, margin + 4, y);
        y += 3.5;
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // DIRECTORY PRESENCE
  // ═══════════════════════════════════════════════════════════════════
  if (report.rawDirectories?.length > 0) {
    const knownDirs = report.rawDirectories.filter(d => d.found !== null);
    if (knownDirs.length > 0) {
      sectionHeader("Directory Presence");
      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["Directory", "Found", "NAP Correct"]],
        body: knownDirs.map(d => [
          d.name,
          d.found ? "Yes" : "No",
          d.found ? (d.napCorrect ? "Yes" : "No") : "—",
        ]),
        styles: { fontSize: 7, cellPadding: 1.5 },
        headStyles: { fillColor: BRAND.navy, textColor: BRAND.white, fontStyle: "bold" },
        didParseCell: (data: any) => {
          if (data.section === "body" && data.column.index === 1) {
            data.cell.styles.textColor = data.cell.raw === "Yes" ? [16, 185, 129] : [239, 68, 68];
            data.cell.styles.fontStyle = "bold";
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }
  }

  // Add page footers
  addFooter();

  // Save
  const filename = `RankedFirst_Audit_${report.meta.businessName.replace(/\s+/g, "_")}_${new Date(report.meta.auditDate).toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
